name: Build Browser to EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-cache: 'pip'

    - name: Install Dependencies
      run: |
        pip install PyQt5 PyQtWebEngine pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onedir --windowed browser.py

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: MyBrowser-EXE
        path: dist/
